version: '3.4'

services:
  csv_automation:
    image: csv_automation
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      [
        "sh",
        "-c",
        "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 export_applications_to_csv.py "
      ]
    ports:
      - 5678:5678
